### ISSUE TITLE
Replay demo rosbag failed and Dreamview restart failed

### ISSUE THREAD

**Issue by lyxzhl** [ApolloAuto/apollo#2928]
Question 1:
I downloaded demo_2.0.bag successfully. But when I execute "rosbag play -l ./docs/demo_guide/demo_2.0.bag" if failed as following message.

Traceback (most recent call last):
  File "/usr/bin/rosbag", line 34, in <module>
    import rosbag
  File "/usr/lib/python2.7/dist-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/usr/lib/python2.7/dist-packages/rosbag/bag.py", line 58, in <module>
    import genmsg
ImportError: No module named genmsg

Could you let me know how can i fix this error?

Question 2:
I started Dreamview by http://localhost:8888 successfully. But after restarting ubuntu, the page said "Firefox cannot establish connection to localhost:8888". Could you let me know how can i fix this error?

**Comment by h0wser** [comment]
I have a similair issue, the /tmp/supervisord.log file tells me that both monitor and dreamview exit because of a SIGABRT signal. Not sure where to go from here

**Comment by h0wser** [comment]
Found the logs for dreamview and monitor, it was trying to access .ros, which was owned by root and not my user,

`chown -R user ~/. `

fixed the problem

**Comment by lyxzhl** [comment]
@h0wser Do you mean 
`chown -R user ~/.`
can fix the problem of launching localhost:8888? I tried this but the Firefox still cannot open localhost:8888.

Besides, there is not /tmp/supervisord.log such a file in my folder.

**Comment by natashadsouza** [comment]
@lyxzhl are you still experiencing the error? Closing this issue currently, but feel free to open it should you have any more questions.
